name: Trigger

on:
  pull_request:
  push:

jobs:
  p81m57:
    name: 'Php-8.1-Mysql-5.7'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.1'
      mysql: '5.7.37'

  p82m80:
    name: 'Php-8.2-Mysql-8.0'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.2'
      mysql: '8.0'

  p82m80shop:
    name: 'Php-8.2-Mysql-8.0-shop'
    uses: ./.github/workflows/shop.yml
    secrets: inherit